import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, CircleGauge, Scale, Sparkles } from "lucide-react";
import { BoardSignal } from "@/components/intelligence/board-signal";
import { EvidenceDisclosure } from "@/components/intelligence/evidence-disclosure";
import { competitorFocus, findings, reportMeta } from "@/lib/market-report";
import { createClient } from "@/lib/supabase/server";
import type { BoardSignal as BoardSignalType } from "@/schemas/executive";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: { absolute: "Financial Services Transformation Intelligence | Ross Bloomfield" }, description: "Board-level intelligence on AI, digital transformation, competitors, regulation and customer change across Irish and global financial services.", alternates: { canonical: "/intelligence" }, openGraph: { title: "Financial Services Transformation Intelligence", description: "Know what is changing before it changes your business.", url: "/intelligence", type: "website" } };

const signals: BoardSignalType[] = [
  { id:"opportunity-ai-advice", category:"opportunity", title:"AI-enabled advice at scale", summary:"Governed AI can extend relevant guidance while preserving accountable human judgement.", score:5, rag:"green", trend:"up", evidenceConfidence:"high", sourceCount:1, primarySourceCount:1, href:"/intelligence/ai" },
  { id:"threat-execution-gap", category:"threat", title:"The execution gap is widening", summary:"Leaders are moving from pilots to disclosed production value and integrated relationships.", score:5, rag:"red", trend:"up", evidenceConfidence:"high", sourceCount:2, primarySourceCount:2, href:"/intelligence/competitors" },
  { id:"customer-affordability", category:"customer_shift", title:"Affordability is increasing demand for guidance", summary:"Customers need clearer trade-offs, proactive support and dependable recovery when service fails.", score:4, rag:"amber", trend:"up", evidenceConfidence:"medium", sourceCount:1, primarySourceCount:1, href:"/intelligence/customers" },
  { id:"reg-resilience", category:"regulatory_risk", title:"Resilience has entered the evidence phase", summary:"Boards must demonstrate service outcomes, dependencies and remediation under disruption.", score:5, rag:"red", trend:"up", evidenceConfidence:"high", sourceCount:1, primarySourceCount:1, href:"/intelligence/regulation" },
  { id:"tech-core", category:"technology_shift", title:"Modernisation is moving into the core estate", summary:"Cloud, data, identity and workflow are becoming one operating-model agenda.", score:4, rag:"amber", trend:"up", evidenceConfidence:"high", sourceCount:1, primarySourceCount:1, href:"/intelligence/ai" },
];

const categories = [
  { label:"Signals", href:"/intelligence/signals", icon:CircleGauge, conclusion:"Production execution is separating from experimentation", trend:"↑ Strengthening", count:"9 relevant signals", confidence:"High confidence" },
  { label:"Competitors", href:"/intelligence/competitors", icon:Building2, conclusion:"Competitive pressure is increasing across integrated relationships and production AI", trend:"↑ Increasing", count:`${competitorFocus.length} organisations monitored`, confidence:"High confidence" },
  { label:"AI & transformation", href:"/intelligence/ai", icon:Sparkles, conclusion:findings.ai[0].title, trend:"↑ Accelerating", count:"3 significant developments", confidence:"High confidence" },
  { label:"Regulation", href:"/intelligence/regulation", icon:Scale, conclusion:findings.regulation[0].title, trend:"↑ Urgent", count:"3 priority movements", confidence:"High confidence" },
];

export default async function Page() {
  let reports: { slug:string; title:string; executive_headline:string; overall_assessment:string; published_at:string|null; content:unknown }[] | null = null;
  try { const supabase = await createClient(); const result = await supabase.from("reports").select("slug,title,executive_headline,overall_assessment,published_at,content").eq("is_published", true).order("published_at", { ascending: false }).limit(2); reports = result.data; } catch { /* Render the reviewed fallback when public database configuration is unavailable. */ }
  const report = reports?.[0];
  const reportHref = report ? `/intelligence/reports/${report.slug}` : "/intelligence/reports";
  const published = report?.published_at ? new Intl.DateTimeFormat("en-IE", { dateStyle:"long" }).format(new Date(report.published_at)) : reportMeta.period;
  const topFindings = [findings.regulation[0], findings.ai[0], findings.customer[1], findings.regulation[1], findings.customer[2]];
  const materiality = { critical: signals.filter((item) => item.score === 5).length, significant: signals.filter((item) => item.score === 4).length, watchlist: signals.filter((item) => item.score <= 3).length };
  return <div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 sm:py-8">
    <section className="overflow-hidden rounded-2xl bg-[var(--purple-dark)] p-6 text-white sm:p-9"><div className="grid gap-8 xl:grid-cols-[1.25fr_.75fr]"><div><p className="label text-orange-200">FINANCIAL SERVICES TRANSFORMATION INTELLIGENCE</p><h1 className="mt-3 max-w-4xl text-3xl font-semibold leading-tight sm:text-5xl">Know what is changing before it changes your business.</h1><p className="mt-5 max-w-3xl leading-7 text-purple-100">Board-level intelligence that identifies consequential changes across competitors, customers, technology and regulation — and translates them into decisions for senior leaders.</p><p className="mt-3 text-sm font-semibold text-orange-200">Ireland first. Global signals where they matter.</p><div className="mt-6 flex flex-wrap gap-3"><Link className="rounded-lg bg-[var(--orange)] px-4 py-3 text-sm font-bold text-white" href={reportHref}>View this week&apos;s briefing</Link><Link className="rounded-lg border border-white/30 px-4 py-3 text-sm font-bold" href="/intelligence/signals">Explore intelligence</Link></div></div><aside className="rounded-xl border border-white/15 bg-white/10 p-5"><p className="label text-orange-200">THIS WEEK&apos;S ASSESSMENT</p><p className="mt-3 text-sm text-purple-100">{published}</p><div className="mt-4 flex items-center justify-between gap-4"><span className="text-sm">Board attention</span><strong className="rounded-full bg-red-100 px-3 py-1 text-xs text-red-800">HIGH</strong></div><h2 className="mt-5 text-xl font-semibold">{report?.executive_headline ?? reportMeta.headline}</h2><p className="mt-3 text-sm leading-6 text-purple-100">{report?.overall_assessment ?? reportMeta.assessment}</p><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Metric value={String(materiality.critical)} label="Critical"/><Metric value={String(materiality.significant)} label="Significant"/><Metric value={String(materiality.watchlist)} label="Watchlist"/></div><p className="mt-4 text-xs text-purple-100">Evidence confidence: High</p><Link className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-orange-200" href={reportHref}>Read 8-minute briefing <ArrowRight size={15}/></Link></aside></div></section>
    <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="label text-[var(--purple)]">CEO DASHBOARD</p><h2 className="mt-2 text-2xl font-semibold">The decisions behind the signals</h2></div><div className="rounded-xl bg-white px-5 py-3 text-sm"><span className="text-[var(--muted)]">Competitive pressure </span><strong className="text-[var(--red)]">INCREASING ↑</strong><span className="sr-only"> strengthening versus previous report</span></div></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{signals.map((signal)=><BoardSignal key={signal.id} signal={signal}/>)}</div></section>
    <section className="mt-7 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-[var(--line)] bg-white p-6"><p className="label text-[var(--purple)]">THIS WEEK IN ONE MINUTE</p><h2 className="mt-2 text-2xl font-semibold">What changed—and why it matters</h2><ol className="mt-4 divide-y divide-[var(--line)]">{topFindings.map((item,index)=><li className="grid gap-2 py-4 sm:grid-cols-[2rem_1fr]" key={item.title}><span className="finding-number">{index+1}</span><div><h3 className="font-semibold">{item.title}</h3><p className="mt-1 text-sm leading-6 text-[var(--muted)]"><strong>Implication:</strong> {item.implication}</p></div></li>)}</ol><Link className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-[var(--purple)]" href={reportHref}>Read full briefing <ArrowRight size={15}/></Link></div><aside className="rounded-2xl border border-[var(--line)] bg-white p-6"><p className="label text-[var(--purple)]">EXECUTIVE RESPONSE</p><h2 className="mt-2 text-2xl font-semibold">What leadership should do now</h2><div className="mt-4 space-y-3">{findings.actions.map((item,index)=><article className="rounded-xl bg-[var(--paper)] p-4" key={item.title}><p className="label text-[var(--orange)]">{["ACCELERATE","DEFEND","PREPARE"][index]}</p><h3 className="mt-2 font-semibold">{item.title}</h3><dl className="mt-3 grid gap-2 text-sm"><div><dt className="font-semibold">Decision required</dt><dd className="text-[var(--muted)]">{item.implication}</dd></div><div className="grid grid-cols-2 gap-3"><div><dt className="font-semibold">Owner</dt><dd className="text-[var(--muted)]">{["CDIO / CRO","CEO / CCO","CRO / COO"][index]}</dd></div><div><dt className="font-semibold">Timing</dt><dd className="text-[var(--muted)]">30 days</dd></div></div></dl></article>)}</div><Link className="mt-4 inline-flex text-sm font-semibold text-[var(--purple)]" href="/intelligence/actions">View all actions →</Link></aside></section>
    <section className="mt-7"><p className="label text-[var(--purple)]">EXPLORE INTELLIGENCE</p><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{categories.map(({icon:Icon,...item})=><Link className="group rounded-2xl border border-[var(--line)] bg-white p-5" href={item.href} key={item.label}><Icon className="text-[var(--purple)]" size={19}/><p className="label mt-5 text-[var(--orange)]">{item.label}</p><h3 className="mt-2 font-semibold leading-snug">{item.conclusion}</h3><p className="mt-3 text-sm font-semibold text-[var(--purple)]">{item.trend}</p><p className="mt-3 text-xs text-[var(--muted)]">{item.count} · {item.confidence}</p></Link>)}</div></section>
    <section className="mt-7 rounded-2xl border border-[var(--line)] bg-white p-6"><p className="label text-[var(--purple)]">EVIDENCE</p><h2 className="mt-2 text-xl font-semibold">See what supports the assessment</h2><EvidenceDisclosure items={[{ title:findings.ai[0].sourceLabel, publisher:"Published company reporting", primary:true, classification:"Declared strategy and performance", claim:findings.ai[0].title, url:findings.ai[0].sourceUrl }, { title:findings.regulation[0].sourceLabel, publisher:"Central Bank of Ireland", primary:true, classification:"Regulatory source", claim:findings.regulation[0].title, url:findings.regulation[0].sourceUrl }]}/></section>
  </div>;
}

function Metric({value,label}:{value:string;label:string}) { return <div className="rounded-lg bg-white/10 p-3"><strong className="block text-lg">{value}</strong><span className="text-[.65rem] text-purple-100">{label}</span></div>; }
