import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { EvidenceDisclosure } from "@/components/intelligence/evidence-disclosure";
import { SectionPage } from "@/components/intelligence/section-page";
import { findings } from "@/lib/market-report";
const all=[...findings.ai,...findings.regulation,...findings.customer];const slugify=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
export function generateStaticParams(){return all.map(item=>({slug:slugify(item.title)}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const item=all.find(row=>slugify(row.title)===slug);return item?{title:item.title,description:item.interpretation,alternates:{canonical:`/intelligence/themes/${slug}`}}:{title:"Signal unavailable"}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const item=all.find(row=>slugify(row.title)===slug);if(!item)notFound();return <SectionPage eyebrow="STRATEGIC THEME" title={item.title} description={item.interpretation}><div className="grid gap-5 xl:grid-cols-[1fr_.7fr]"><section className="rounded-2xl border border-[var(--line)] bg-white p-6"><div className="flex flex-wrap gap-2"><span className="signal-pill">{item.direction==="Accelerating"?"↑ Strengthening":item.direction==="Stable"?"→ Unchanged":"New"}</span><span className="signal-pill">{item.signalKind}</span><span className="signal-pill">{item.strength} confidence</span></div><h2 className="mt-6 text-xl font-semibold">Current assessment</h2><p className="mt-3 leading-7 text-[var(--muted)]">{item.interpretation}</p><h2 className="mt-6 text-xl font-semibold">Ireland read-across</h2><p className="mt-3 leading-7 text-[var(--muted)]">{item.implication}</p><EvidenceDisclosure items={[{title:item.sourceLabel,publisher:item.sourceLabel.split("—")[0],primary:true,classification:"Primary / official evidence",claim:item.title,url:item.sourceUrl}]}/></section><aside className="rounded-2xl border border-[var(--line)] bg-white p-6"><h2 className="text-xl font-semibold">Forward implication</h2><dl className="mt-4 space-y-4 text-sm"><div><dt className="font-semibold">12 months</dt><dd className="mt-1 text-[var(--muted)]">Leadership should convert the signal into an accountable operating choice and measurable outcome.</dd></div><div><dt className="font-semibold">24 months</dt><dd className="mt-1 text-[var(--muted)]">Capability gaps may become structural if governance, data and distribution decisions remain fragmented.</dd></div><div><dt className="font-semibold">Organisations driving the signal</dt><dd className="mt-1 text-[var(--muted)]">See linked evidence; broader entity attribution is currently insufficient for a defensible count.</dd></div></dl><h2 className="mt-7 text-xl font-semibold">Historical timeline</h2><p className="mt-3 text-sm text-[var(--muted)]">New · no prior canonical comparison available.</p></aside></div></SectionPage>}
