import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { EvidenceDisclosure } from "@/components/intelligence/evidence-disclosure";
import { SectionPage } from "@/components/intelligence/section-page";
import { competitorFocus } from "@/lib/market-report";
const slugify=(value:string)=>value.toLowerCase().replaceAll("&","and").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
export function generateStaticParams(){return competitorFocus.map(item=>({slug:slugify(item.organisation)}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const item=competitorFocus.find(row=>slugify(row.organisation)===slug);return item?{title:`${item.organisation} intelligence profile`,description:item.focus,alternates:{canonical:`/intelligence/organisations/${slug}`}}:{title:"Organisation unavailable"}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const item=competitorFocus.find(row=>slugify(row.organisation)===slug);if(!item)notFound();const momentum=["Digital relationship","AI maturity","Wealth integration","Cost transformation","Regulatory risk"];return <SectionPage eyebrow={`${item.sector.toUpperCase()} · ${item.market.toUpperCase()}`} title={item.organisation} description={item.focus}><div className="grid gap-5 xl:grid-cols-[1fr_.65fr]"><section className="rounded-2xl border border-[var(--line)] bg-white p-6"><div className="flex flex-wrap gap-2"><span className="signal-pill">Board signal {item.maturity==="Scaling"?"5":"4"}/5</span><span className="signal-pill">{item.maturity}</span><span className="signal-pill">High confidence</span></div><h2 className="mt-5 text-xl font-semibold">Current assessment</h2><p className="mt-3 leading-7 text-[var(--muted)]">{item.evidence}</p><h2 className="mt-7 text-xl font-semibold">Irish-market read-across</h2><p className="mt-3 leading-7 text-[var(--muted)]">{item.irishReadAcross}</p><EvidenceDisclosure items={[{title:`${item.organisation} official reporting`,publisher:item.organisation,primary:true,classification:"Declared strategy",claim:item.focus,url:item.sourceUrl}]}/></section><aside className="rounded-2xl border border-[var(--line)] bg-white p-6"><h2 className="text-xl font-semibold">Strategic momentum</h2><dl className="mt-4 divide-y divide-[var(--line)]">{momentum.map((label,index)=><div className="flex items-center justify-between py-3 text-sm" key={label}><dt>{label}</dt><dd className="font-bold text-[var(--purple)]">{index<2&&item.maturity==="Scaling"?"↑ Strengthening":"→ Unchanged"}</dd></div>)}</dl><h2 className="mt-7 text-xl font-semibold">Timeline</h2><div className="mt-4 border-l-2 border-purple-200 pl-4"><p className="text-xs text-[var(--muted)]">Current reporting period</p><p className="mt-1 text-sm font-semibold">{item.focus}</p></div><Link className="mt-6 inline-flex text-sm font-semibold text-[var(--purple)]" href="/intelligence/competitors">← Back to competitors</Link></aside></div></SectionPage>}
