"use client";
import { useEffect,useRef,useState } from "react";
import { ExternalLink,X } from "lucide-react";
import type { EvidencePackage,EvidenceSupport } from "@/lib/intelligence/evidence";

export function EvidencePanel({evidence,open,onClose,mobile=false,selectedReferenceId}:{evidence:EvidencePackage|null;open:boolean;onClose:()=>void;mobile?:boolean;selectedReferenceId?:string}){
 const [tab,setTab]=useState<EvidenceSupport>("supporting");const [primaryOnly,setPrimaryOnly]=useState(false);const closeRef=useRef<HTMLButtonElement>(null);const dialogRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!mobile||!open)return;const prior=document.body.style.overflow;const priorFocus=document.activeElement as HTMLElement|null;document.body.style.overflow="hidden";closeRef.current?.focus();return()=>{document.body.style.overflow=prior;priorFocus?.focus()}},[mobile,open]);
 useEffect(()=>{if(!mobile||!open)return;const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){onClose();return}if(event.key!=="Tab")return;const controls=[...(dialogRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled])')??[])];if(!controls.length)return;const first=controls[0],last=controls.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[mobile,open,onClose]);
 useEffect(()=>{if(!open||!selectedReferenceId)return;const timer=window.setTimeout(()=>document.getElementById(`evidence-${selectedReferenceId}`)?.scrollIntoView({block:"center"}),50);return()=>window.clearTimeout(timer)},[open,selectedReferenceId]);
 if(mobile&&!open)return null;
 const references=(evidence?.references??[]).filter(item=>item.supportStrength===tab&&(!primaryOnly||item.primary));
 const panel=<section className="evidence-panel" aria-label="Evidence behind this answer"><header><div><p className="eyebrow">EVIDENCE</p><h2>Evidence behind this answer</h2></div>{mobile&&<button ref={closeRef} className="evidence-close" aria-label="Close evidence" onClick={onClose}><X/></button>}</header><div className="evidence-tabs" role="tablist" aria-label="Evidence type"><button role="tab" aria-selected={tab==="supporting"} onClick={()=>setTab("supporting")}>Supporting <span>{evidence?.references.filter(r=>r.supportStrength==="supporting").length??0}</span></button><button role="tab" aria-selected={tab==="counter"} onClick={()=>setTab("counter")}>Counter-evidence <span>{evidence?.references.filter(r=>r.supportStrength==="counter").length??0}</span></button></div><label className="evidence-filter"><input type="checkbox" checked={primaryOnly} onChange={e=>setPrimaryOnly(e.target.checked)}/> Primary sources only</label>{references.length?<ol className="evidence-list">{references.map(item=><li id={`evidence-${item.id}`} key={item.id}><div className="evidence-card-heading"><span>[{item.rank}] {item.publisher}</span><time>{formatDate(item.publicationDate)}</time></div><h3>{item.title}</h3><p>{item.claimSupported}</p>{(item.passages?.length??0)>1&&<small>{item.passages?.length} relevant passages selected from this source</small>}<dl><div><dt>Source class</dt><dd>{item.primary?"Primary":"Secondary"} · {item.sourceType}</dd></div>{item.classification&&<div><dt>Evidence class</dt><dd>{item.classification}</dd></div>}</dl><a href={item.url} target="_blank" rel="noreferrer">Open source <ExternalLink size={14}/></a></li>)}</ol>:<div className="evidence-empty"><strong>{evidence?.confidence==="insufficient"?"Insufficient evidence":"No evidence in this view"}</strong><p>{evidence?.confidence==="insufficient"?"No approved source records are available to support a substantive answer. No citations have been generated.":"Change the evidence filter to inspect the available references."}</p></div>}<footer>{evidence?<><strong>{label(evidence.confidence)} confidence</strong><span>{evidence.references.length} sources · {evidence.passageCount??evidence.references.length} passages · {evidence.primaryCount} primary · checked {formatDate(evidence.checkedAt)}</span></>:<span>Ask a question to inspect its evidence footprint.</span>}</footer></section>;
 return mobile?<div className="evidence-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div ref={dialogRef} className="evidence-sheet" role="dialog" aria-modal="true" aria-label="Evidence behind this answer">{panel}</div></div>:panel;
}
function formatDate(value:string|null){if(!value)return "Date not recorded";return new Intl.DateTimeFormat("en-IE",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value))}
function label(value:EvidencePackage["confidence"]){return value==="insufficient"?"Insufficient evidence":value[0].toUpperCase()+value.slice(1)}
