"use client";
import Link from "next/link";
import type { CompanyIntelligenceCard,StructuredAnswer as StructuredAnswerData } from "@/lib/intelligence/structured-answer";

export function StructuredAnswer({answer}:{answer:StructuredAnswerData}){
 return <section className="structured-answer" aria-label={answer.title}><h2>{answer.title}</h2>{answer.kind==="company_comparison"?<CompanyComparison companies={answer.companies}/>:answer.kind==="company_cards"?<div className="company-card-grid">{answer.companies.map(company=><CompanyCard key={company.id} company={company}/>)}</div>:answer.kind==="product_comparison"?<ProductComparison answer={answer}/>:<Timeline answer={answer}/>} {answer.limitations.length>0&&<div className="structured-limitations"><strong>Evidence limitations</strong><ul>{answer.limitations.map(item=><li key={item}>{item}</li>)}</ul></div>}</section>;
}
function CompanyComparison({companies}:{companies:CompanyIntelligenceCard[]}){return <div className="structured-table-wrap"><table className="structured-table"><thead><tr><th>Evidence dimension</th>{companies.map(company=><th key={company.id}>{company.name}</th>)}</tr></thead><tbody><Row label="Sector" companies={companies} value={item=>formatTaxonomy(item.sector)}/><Row label="Jurisdiction" companies={companies} value={item=>item.jurisdiction}/><Row label="Current strategy" companies={companies} value={item=>item.strategySummary}/><Row label="Digital evidence" companies={companies} value={item=>item.digitalAssessment}/><Row label="AI evidence" companies={companies} value={item=>item.aiAssessment}/><Row label="Financial highlights" companies={companies} value={item=>item.financialHighlights.length?item.financialHighlights.join(" · "):null}/><Row label="Current strategic theme" companies={companies} value={item=>item.strategicTheme}/><tr><th>Primary evidence</th>{companies.map(company=><td key={company.id}>{company.evidenceReferenceIds.length?company.evidenceReferenceIds.map(id=><a key={id} href={`#evidence-${id}`}>[{id.replace("ref-","")}]</a>):<Insufficient/>}</td>)}</tr></tbody></table></div>}
function Row({label,companies,value}:{label:string;companies:CompanyIntelligenceCard[];value:(company:CompanyIntelligenceCard)=>string|null}){return <tr><th>{label}</th>{companies.map(company=><td key={company.id}>{value(company)??<Insufficient/>}</td>)}</tr>}
function CompanyCard({company}:{company:CompanyIntelligenceCard}){return <article className="structured-company-card"><p>{formatTaxonomy(company.sector)}{company.jurisdiction?` · ${company.jurisdiction}`:""}</p><h3>{company.name}</h3><dl><div><dt>Current strategy</dt><dd>{company.strategySummary??<Insufficient/>}</dd></div><div><dt>Strategic theme</dt><dd>{company.strategicTheme??<Insufficient/>}</dd></div><div><dt>Digital evidence</dt><dd>{company.digitalAssessment??<Insufficient/>}</dd></div><div><dt>AI evidence</dt><dd>{company.aiAssessment??<Insufficient/>}</dd></div>{company.financialHighlights.length>0&&<div><dt>Financial highlights</dt><dd>{company.financialHighlights.join(" · ")}</dd></div>}</dl><Link href={`/intelligence/organisations/${company.slug}`}>View company intelligence →</Link></article>}
function ProductComparison({answer}:{answer:Extract<StructuredAnswerData,{kind:"product_comparison"}>}){return answer.products.length?<div className="product-card-grid">{answer.products.map(product=><article key={product.id} className="structured-product-card"><p>{product.provider}</p><h3>{product.name}</h3><span>{product.category}</span>{product.features.length>0&&<ul>{product.features.map(feature=><li key={feature}>{feature}</li>)}</ul>}{product.journey&&<p><strong>Journey:</strong> {product.journey}</p>}{product.pricing&&<p><strong>Pricing:</strong> {product.pricing}</p>}{product.sourceReferenceId&&<a href={`#evidence-${product.sourceReferenceId}`}>View evidence</a>}</article>)}</div>:<EmptyState>No verified product records match this question.</EmptyState>}
function Timeline({answer}:{answer:Extract<StructuredAnswerData,{kind:"timeline"}>}){return answer.events.length?<ol className="structured-timeline">{answer.events.map(event=><li key={event.id}><time>{event.date??"Date not recorded"}</time><h3>{event.label}</h3><p>{event.summary}</p>{event.referenceId&&<a href={`#evidence-${event.referenceId}`}>View evidence</a>}</li>)}</ol>:<EmptyState>No verified dated events match this question.</EmptyState>}
function EmptyState({children}:{children:string}){return <p className="structured-empty"><strong>Insufficient evidence</strong><span>{children}</span></p>}
function Insufficient(){return <span className="insufficient-label">Insufficient evidence</span>}
function formatTaxonomy(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,character=>character.toUpperCase())}
